### ISSUE TITLE
Différentiation questions/consignes

### ISSUE THREAD

**Issue by JulietteSiebering** [JulietteSiebering/GL02_PlanForYou#1]
Les consignes sont traitées comme des questions, il faut y répondre pour accéder à la suite.

**Comment by igagniere** [comment]
EX-04 : Simulation d’examen pour étudiant

**Comment by igagniere** [comment]
finito pipo mais pas sur la bonne version :'))

**Comment by igagniere** [comment]
Bon c'est bon je crois
