### ISSUE TITLE
Revoir Regex oui/non et création Vcard

### ISSUE THREAD

**Issue by JulietteSiebering** [JulietteSiebering/GL02_PlanForYou#9]
Faire en sorte que des réponses telles que oiuytrhjk ou nwsfvhju ne soient pas acceptées pour oui et non.
Egalement pour les nom/prénoms qui peuevent être tout et n'importe quoi

**Comment by Paug09** [comment]
Ajout d'un fonction et d'un regex pour les verifier

**Comment by Paug09** [comment]
Ajout d'un fonction et d'une ligne d eregex pour les verifier
